### ISSUE TITLE
Does not work with Nvidia Driver 591.44

### ISSUE THREAD

**Issue by majorglory07** [juvlarN/vibranceGUI#149]
Digital vibrance setting not working with newest Nvidia Driver 591.44.

Only tested with CS2.

Update: I was able to get digital vibrance to work by unchecking "Override to reference mode" under Adjust desktop color settings in Nvidia Control Panel. This setting seems to limit the ability to adjust Digital Vibrance. Not sure if that has always been the case or if setting was enabled by latest driver version.

**Comment by Ren0X1** [comment]
any update about this?

**Comment by majorglory07** [comment]
I am using vibranceGUI 2.5.0 with 591.74 with no issues.

**Comment by Ren0X1** [comment]
i alredy downgrade to 581.80 and is working fine, hope  they can fix it before we are forced to change drivers due to a new game release or CS2 update

**Comment by juv** [comment]
> Update: I was able to get digital vibrance to work by unchecking "Override to reference mode" under Adjust desktop color settings in Nvidia Control Panel. This setting seems to limit the ability to adjust Digital Vibrance. Not sure if that has always been the case or if setting was enabled by latest driver version.

Hi, yes I think this is the reason.

The NVIDIA Control Panel [documentation ](https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nvdsp/CS_Adjust_Color_Settings_Advanced.htm) says:
>  If the Override to reference mode check box is selected, these controls are set to default values but are greyed out and cannot be changed.  

Besides of that, was this solved by a new NVIDIA driver version in the meantime?

**Comment by Ren0X1** [comment]
The last time I tried it after seeing the issue posted on GitHub, I had already disabled “override reference mode,” but vibranceGUI still didn't work until I downgraded.

**Comment by majorglory07** [comment]
> Besides of that, was this solved by a new NVIDIA driver version in the meantime?

I ended up switching to vibranceGUI v2.5.0 beta and have no issues with newest Nvidia Driver 591.86.

**Comment by SwatX18** [comment]
A way to narrow this down, rather than another "try this build" suggestion.

The thread never settled which of two things is happening: the driver refusing DVC outright, or vibranceGUI failing to apply it. Those need completely different fixes, and right now nobody can tell them apart — @Ren0X1 in particular reported it still failing with *Override to reference mode* already unchecked, which rules out the explanation juv found.

A fork build I maintain adds a command line flag that isolates it, because it involves no game at all:

```
vibrance.GUI.exe --set-vibrance 63
```

That sets the Windows-level vibrance directly — the level used while no configured game is in the foreground — and then starts normally. Valid range is 0–63 on NVIDIA.

- **Screen visibly changes** → the driver is accepting DVC writes on 591.44+, and the problem is in game detection or in when the level gets applied. That is fixable.
- **Nothing happens** → the driver is refusing the write, and no version of vibranceGUI can help. That would also answer juv's question above about whether a later driver solved it.

Build: **[v2.7.0](https://github.com/SwatX18/vibranceGUI/releases/tag/v2.7.0)** — my fork, unsigned, not an official juv build, and I have no evidence it fixes this issue. I am offering it as a diagnostic, not as a fix.

@majorglory07 — no need on your side if v2.5.0 is working for you; the question is really for anyone still stuck.
